### ISSUE TITLE
undefined reference to `sdl_graphics_gl_context_unref'

### ISSUE THREAD

**Issue by wayneker** [sdl2-vapi/sdl2-vapi#11]
Hi,

The following line:
Graphics.GL.Context context = new GL.Context(window);
throws this error when compiling:
SDLSample.vala.c:(.text+0x5f1): undefined reference to `sdl_graphics_gl_context_unref'

Suspect that unref_function="SDL_GL_DeleteContext" is missing?

Regards,
Wayne.

**Comment by desiderantes** [comment]
Well, actually the error happens because the class was not marked as compact, and that since SDL_GL_CreateContext can return NULL, it shouldn't be a constructor, it should be fixed in fc3023c62489782aac289ca7fa2582ea57c7e2bb, please try it with `Graphics.GL.Context? context = GL.Context.create(window);`

**Comment by wayneker** [comment]
I've tried it as you suggested. I now get the following error when compiling:
SDLSample.vala.c:(.text+0x1d48): undefined reference to `sdl_graphics_gl_context_free'
Adding free_function="SDL_GL_DeleteContext" to the vapi file makes the error go away.

**Comment by desiderantes** [comment]
Yes, i forgot to replace the related CCode, please try again after updating to 7e5d5b86e9490676c871e19da1e85c768ef01fc5

**Comment by wayneker** [comment]
It's working perfect now.
Thanks.
